title = "Ozan Hanedan"
baseURL = "https://ozanhanedan.com.tr/"
theme = "resume-ohanedan"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = ""
emailText = "contact with me"
email = "oznhndn@gmail.com"
favicon = ""
firstName = "Ozan"
lastName = "Hanedan"
phone = ""
profileImage = "img/ohanedan.png"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showBlog = false
showQr = false
showSkills = false

[params.google]

[params.google.analytics]
trackerID = "UA-90123434-4"

[[params.handles]]
link = "https://www.linkedin.com/in/ozanhanedan/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/ohanedan"
name = "GitHub"

[[params.handles]]
link = "https://www.youtube.com/user/oznhndn/videos"
name = "Youtube"

[[params.handles]]
link = "https://twitter.com/ozanhanedan"
name = "Twitter"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
